services:
    database:
        image: postgres:17
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: linkmate
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
